### ISSUE TITLE
render

### ISSUE THREAD

**Issue by amohrland** [seanstrom/counter-from-scratch#1]
So I understand, is it the `render` function that actually performs the side effect? (https://github.com/seanstrom/counter-from-scratch/blob/master/src/main.js#L6) Like, running that will actually update the dom?

**Comment by seanstrom** [comment]
`render` takes in ‘document’, a dom node, and a function that when called with document will return a tree of dom nodes. 
`render` will essentially create that dom tree and decide whether is going to render that tree or replace the original tree with that tree.
`render` does perform the high level side effects to the dom.
